export const PLAYER_PROFILES = [
  {
    id: '1',
    name: 'LalitoPro777',
    verified: true,
    level: 34,
    rank: 'Radiante',
    game: 'Valorant',
    style: 'Competitivo',
    role: 'Duelista',
    availability: 'Noche',
    countryISO: 'CL',
    countryName: 'Chile',
    compatibility: 0.92,
    karma: 1250,
    onlineStatus: 'En línea',
    last_act: 'En línea',
    victorias: '68%',
    partidas: '1,248',
    profilePic: 'https://media.valorant-api.com/agents/add6443a-41bd-e414-f6ad-e58d267f4e95/displayicon.png',
    games: [{ id: 'valorant', logo: 'https://logo.clearbit.com/valorant.com' }]
  },
  {
    id: '2',
    name: 'YasuoGod_Sorek',
    verified: false,
    level: 45,
    rank: 'Maestro',
    game: 'LoL',
    style: 'Competitivo',
    role: 'Mid',
    availability: 'Noche',
    countryISO: 'CL',
    countryName: 'Chile',
    compatibility: 0.78,
    karma: 950,
    onlineStatus: 'Ausente',
    last_act: 'hace 5 min.',
    victorias: '55%',
    partidas: '980',
    profilePic: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_0.jpg',
    games: [{ id: 'lol', logo: 'https://logo.clearbit.com/leagueoflegends.com' }]
  },
  {
    id: '3',
    name: 'PudgeEnjoyer',
    verified: true,
    level: 12,
    rank: 'Legend',
    game: 'Dota 2',
    style: 'Chill',
    role: 'Support',
    availability: 'Noche',
    countryISO: 'CL',
    countryName: 'Chile',
    compatibility: 0.85,
    karma: 2100,
    onlineStatus: 'En línea',
    last_act: 'En línea',
    victorias: '52%',
    partidas: '450',
    profilePic: 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pudge.png',
    games: [{ id: 'dota2', logo: 'https://logo.clearbit.com/dota2.com' }]
  }
];